In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [6]:
# pip install tensorflow

In [3]:
tf.__version__

'2.21.0'

In [4]:
dataset =pd.read_csv(r"C:\Users\prati\Downloads\Churn_Modelling.csv")
X= dataset.iloc[:,3:-1].values
y =dataset.iloc[:,-1].values

In [5]:
dataset

,apst,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,delhi,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,bangalore,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,delhi,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,delhi,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,bangalore,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,delhi,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,delhi,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,delhi,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,mumbai,Male,42,3,75075.31,2,1,0,92888.52,1


In [7]:
dataset.head()

,apst,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,delhi,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,bangalore,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,delhi,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,delhi,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,bangalore,Female,43,2,125510.82,1,1,1,79084.10,0


In [9]:
print(X)

[[619 'delhi' 'Female' ... 1 1 101348.88]
 [608 'bangalore' 'Female' ... 0 1 112542.58]
 [502 'delhi' 'Female' ... 1 0 113931.57]
 ...
 [709 'delhi' 'Female' ... 0 1 42085.58]
 [772 'mumbai' 'Male' ... 1 0 92888.52]
 [792 'delhi' 'Female' ... 1 0 38190.78]]


In [10]:
y

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

In [11]:
dataset.head(2)

,apst,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,delhi,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,bangalore,Female,41,1,83807.86,1,0,1,112542.58,0


In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [14]:
print(X)

[[619 'delhi' 0 ... 1 1 101348.88]
 [608 'bangalore' 0 ... 0 1 112542.58]
 [502 'delhi' 0 ... 1 0 113931.57]
 ...
 [709 'delhi' 0 ... 0 1 42085.58]
 [772 'mumbai' 1 ... 1 0 92888.52]
 [792 'delhi' 0 ... 1 0 38190.78]]


In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])], remainder ='passthrough')
X = np.array(ct.fit_transform(X))

In [19]:
print(X)

[[0.0 1.0 0.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [0.0 1.0 0.0 ... 1 0 113931.57]
 ...
 [0.0 1.0 0.0 ... 0 1 42085.58]
 [0.0 0.0 1.0 ... 1 0 92888.52]
 [0.0 1.0 0.0 ... 1 0 38190.78]]


In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [23]:
print(X)

[[-0.57380915  0.99720391 -0.57873591 ...  0.64609167  0.97024255
   0.02188649]
 [ 1.74273971 -1.00280393 -0.57873591 ... -1.54776799  0.97024255
   0.21653375]
 [-0.57380915  0.99720391 -0.57873591 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [-0.57380915  0.99720391 -0.57873591 ... -1.54776799  0.97024255
  -1.00864308]
 [-0.57380915 -1.00280393  1.72790383 ...  0.64609167 -1.03067011
  -0.12523071]
 [-0.57380915  0.99720391 -0.57873591 ...  0.64609167 -1.03067011
  -1.07636976]]


In [24]:
from sklearn.model_selection import train_test_split
X_train , X_test ,y_train ,y_test = train_test_split(X,y, test_size =0.2 ,random_state =0)

In [25]:
print (X_train.shape)
print (X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 12)
(2000, 12)
(8000,)
(2000,)


# ANN Model Building Architecture

In [32]:
ann = tf.keras.models.Sequential() # Sequential = establish layer one after another

In [34]:
ann.add(tf.keras.layers.Dense(units=6))  #input layer ,  Dense --> Fully Connected

In [38]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))  #Hidden Layer 1

In [37]:
#ann.add(tf.keras.layers.Dense(units=5, activation='relu'))  #Hidden Layer 2

In [ ]:
#ann.add(tf.keras.layers.Dense(units=4, activation='relu'))  #Hidden Layer 3

In [39]:
ann.add(tf.keras.layers.Dense(units=1 ,activation='sigmoid')) #Output Layer

In [40]:
ann.compile(optimizer ='adam', loss ='binary_crossentropy' , metrics = ['accuracy'])

In [41]:
ann.fit(X_train ,y_train , batch_size =32 , epochs =70)

Epoch 1/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.6453 - loss: 0.6408
Epoch 2/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8009 - loss: 0.4491
Epoch 3/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8091 - loss: 0.4259
Epoch 4/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8198 - loss: 0.4163
Epoch 5/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8356 - loss: 0.3928
Epoch 6/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8453 - loss: 0.3689
Epoch 7/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8526 - loss: 0.3625
Epoch 8/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8531 - loss: 0.3591
Epoch 9/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8545 - loss: 0.3563
Epoch 10/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8580 - loss: 0.3524
Epoch 11/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8568 - loss: 0.3509
Epoch 12/70
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [43]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

print(
    np.concatenate(
        (y_pred.reshape(len(y_pred), 1),
         y_test.reshape(len(y_test), 1)),
        1
    )
)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [44]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test , y_pred)
print(cm)

[[1510   85]
 [ 193  212]]


In [45]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test , y_pred)
print(ac)

0.861
